# Dockerfile.rails
FROM ruby:3.1.3 as fetch-service

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install rails
RUN gem install rails bundler
#RUN chown -R user:user /opt/app
WORKDIR /opt/app

COPY . .
RUN gem install bundler
RUN bundle install
RUN rails db:drop db:setup db:seed
CMD bundle exec rails s -b 0.0.0.0
